### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by spinda** [rust-lang/rust-guidelines#53]
From the README:

> # THIS REPOSITORY HAS MOVED
> 
> Please see the [src/doc/style](https://github.com/rust-lang/rust/tree/master/src/doc/style) subdirectory of [https://github.com/rust-lang/rust/](https://github.com/rust-lang/rust/)

There is no longer any `src/doc/style` directory in rust-lang/rust. Where has the style guide gone?

**Comment by killercup** [comment]
See <https://github.com/rust-lang/rust/pull/35124> by @steveklabnik for an rationale on the removal and <https://github.com/rust-lang-nursery/fmt-rfcs> for the new repo for style RFCs. 1.12 seems to be last release with this version of the style guidelines in the docs (you can find the rendered version [here](https://doc.rust-lang.org/1.12.0/style/README.html)).
